import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Classic Teak Panel Door",
    category: "door",
    pricePerSqft: 850,
    description:
      "Crafted from premium Grade-A teak wood, this classic panel door combines traditional craftsmanship with modern finishing. Features deep-relief carved panels, precision-jointed frame, and a hand-applied oil finish that highlights the natural grain. Ideal for main entrances and bedrooms.",
    image: "https://placehold.co/800x600/165a9e/ffffff?text=Teak+Panel+Door",
    material: "Grade-A Teak Wood",
    features: [
      "Deep-relief carved panels",
      "Precision-jointed hardwood frame",
      "Hand-applied oil finish",
      "Anti-warp treatment",
      "Available in custom sizes",
    ],
    inStock: true,
  },
  {
    id: "2",
    name: "Steel Security Door",
    category: "door",
    pricePerSqft: 1200,
    description:
      "Heavy-duty galvanised steel door engineered for maximum security without sacrificing aesthetics. Features a multi-point locking system, reinforced steel core, and powder-coat finish resistant to corrosion and scratches. Certified for commercial and residential high-security applications.",
    image: "https://placehold.co/800x600/0f3d6e/ffffff?text=Steel+Security+Door",
    material: "Galvanised Steel",
    features: [
      "Multi-point locking system",
      "Reinforced 3mm steel core",
      "Powder-coat corrosion-resistant finish",
      "Anti-drill, anti-pick lock cylinder",
      "Fire-rated option available",
    ],
    inStock: true,
  },
  {
    id: "3",
    name: "uPVC French Window",
    category: "window",
    pricePerSqft: 650,
    description:
      "Energy-efficient uPVC French windows featuring a slim-profile frame with double-glazed Low-E glass. Provides excellent thermal insulation, UV protection, and sound attenuation. The casement design opens outward for maximum ventilation with a sleek, European aesthetic.",
    image: "https://placehold.co/800x600/165a9e/ffffff?text=uPVC+French+Window",
    material: "uPVC with Double Glazing",
    features: [
      "Low-E double-glazed glass",
      "Thermal break technology",
      "UV-protective coating",
      "40 dB sound insulation",
      "Concealed multi-point lock",
    ],
    inStock: true,
  },
  {
    id: "4",
    name: "Aluminium Sliding Door",
    category: "door",
    pricePerSqft: 950,
    description:
      "Sleek aluminium sliding door system designed for large openings. Features a heavy-duty stainless-steel track, smooth ball-bearing rollers, and a powder-coated frame available in 20+ RAL colours. Perfect for connecting indoor and outdoor living spaces with minimal frame obstruction.",
    image: "https://placehold.co/800x600/1a6cb8/ffffff?text=Aluminium+Sliding+Door",
    material: "Aluminium Alloy",
    features: [
      "Heavy-duty stainless-steel track",
      "Smooth ball-bearing roller system",
      "20+ powder-coat colour options",
      "Adjustable height and alignment",
      "Mosquito mesh track included",
    ],
    inStock: true,
  },
  {
    id: "5",
    name: "Hardwood Casement Window",
    category: "window",
    pricePerSqft: 780,
    description:
      "Premium hardwood casement windows with a mortise-and-tenon joinery for exceptional structural integrity. Finished with weather-resistant exterior paint and internal lacquer. Single or double casement configurations available, with optional decorative glazing bars.",
    image: "https://placehold.co/800x600/0f3d6e/ffffff?text=Hardwood+Window",
    material: "Engineered Hardwood",
    features: [
      "Mortise-and-tenon joinery",
      "Weather-resistant exterior finish",
      "Espagnolette locking mechanism",
      "Optional decorative glazing bars",
      "FSC-certified sustainable timber",
    ],
    inStock: true,
  },
  {
    id: "6",
    name: "Glass Partition Door",
    category: "door",
    pricePerSqft: 1100,
    description:
      "Contemporary full-height glass partition door ideal for offices, showrooms, and modern homes. Uses 12mm toughened safety glass with stainless-steel pivot hinges and a flush pull handle. Available in clear, frosted, or tinted glass variants.",
    image: "https://placehold.co/800x600/165a9e/ffffff?text=Glass+Partition+Door",
    material: "12mm Toughened Safety Glass",
    features: [
      "12mm toughened safety glass",
      "Stainless-steel pivot hinges",
      "Floor-spring or overhead closer",
      "Clear, frosted, or tinted options",
      "Frameless or slim-frame design",
    ],
    inStock: false,
  },
  {
    id: "7",
    name: "WPC Flush Door",
    category: "door",
    pricePerSqft: 720,
    description:
      "Wood-Plastic Composite flush door — 100% waterproof and termite-proof, making it the ideal choice for bathrooms, kitchens, and humid environments. Smooth, paintable surface available in solid core and hollow core variants.",
    image: "https://placehold.co/800x600/1a6cb8/ffffff?text=WPC+Flush+Door",
    material: "Wood-Plastic Composite",
    features: [
      "100% waterproof and termite-proof",
      "Smooth paintable surface",
      "Solid and hollow core options",
      "No warping or swelling",
      "Eco-friendly material",
    ],
    inStock: true,
  },
  {
    id: "8",
    name: "Louvred Ventilation Window",
    category: "window",
    pricePerSqft: 580,
    description:
      "Anodised aluminium louvred window designed to maximise natural ventilation while providing privacy. Fixed or adjustable blade options, with fly-screen frame as standard. Commonly used in utility areas, bathrooms, and stairwells.",
    image: "https://placehold.co/800x600/0f3d6e/ffffff?text=Louvred+Window",
    material: "Anodised Aluminium",
    features: [
      "Adjustable blade angle control",
      "Fly-screen frame as standard",
      "Anodised corrosion resistance",
      "Suitable for coastal climates",
      "Minimal maintenance required",
    ],
    inStock: true,
  },
];
